  <div id="vsebina" class="col-lg-10 col-md-9 col-sm-9 cd">
      <div class = "ena">
      <h2><?php echo ucfirst($this->input->post('username')); ?>, izpolni naslednji vprašalnik</h2>
      <form name = "vprasalnik" action = "rezultat" method="post">
          <p></p>
          <table border = "0">
              <tr>
                  <th>Vprašalnik</th>
                  <th colspan = "5">Možnosti</th>
              </tr>    

              <tr>
                <td>Prvo testno vprašanje</td>
                <td>1: <input type="radio" required name="vpra1" value="1"></td>
                <td>2: <input type="radio" required name="vpra1" value="2"></td>
                <td>3: <input type="radio" required name="vpra1" value="3"></td>
                <td>4: <input type="radio" required name="vpra1" value="4"></td>
                <td>5: <input type="radio" required name="vpra1" value="5"></td>
            </tr> 
            <tr>
                <td>Drugo testno vprašanje</td>
                <td>1: <input type="radio" required name="vpra2" value="1"></td>
                <td>2: <input type="radio" required name="vpra2" value="2"></td>
                <td>3: <input type="radio" required name="vpra2" value="3"></td>
                <td>4: <input type="radio" required name="vpra2" value="4"></td>
                <td>5: <input type="radio" required name="vpra2" value="5"></td>
                </tr>
            <tr>
                <td>Tretje testno vprašanje</td>
                <td>1: <input type="radio" required name="vpra3" value="1"></td>
                <td>2: <input type="radio" required name="vpra3" value="2"></td>
                <td>3: <input type="radio" required name="vpra3" value="3"></td>
                <td>4: <input type="radio" required name="vpra3" value="4"></td>
                <td>5: <input type="radio" required name="vpra3" value="5"></td>    
          </table>    
          <br>
          <input type="submit" required value="Posreduj podatke">
      </form>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc neque ex, pharetra eu mauris at, suscipit volutpat orci. Praesent semper diam eu tellus aliquet, a faucibus sem posuere. Vestibulum congue, nisi eu laoreet scelerisque, lectus velit molestie sem, ac vehicula massa orci ut tellus. Cras convallis et lacus id consequat. Nam odio erat, interdum vel facilisis id, cursus eget arcu. Nam commodo sit amet arcu in egestas. Nullam posuere ut leo id tincidunt. 
Donec odio felis, eleifend eu pretium at, ornare eu urna. Aliquam auctor efficitur sagittis. Maecenas eget mi nulla. Pellentesque id erat diam. Morbi sed nisi massa. Suspendisse quis dapibus est, et accumsan dui. In hac habitasse platea dictumst. Sed posuere pellentesque cursus. Vivamus ut lectus mi. Fusce luctus orci vel finibus iaculis. Phasellus tincidunt felis nisi, et rutrum quam vulputate a. Donec sed mi elit. Nulla a arcu urna. Maecenas lacus urna, lacinia id justo nec, aliquam ornare quam. Suspendisse eu sapien ut ante pretium lobortis id in leo. Morbi pretium elit augue, non vehicula erat finibus eget. 
Proin a dui quis mi viverra mollis at ut nisi. Donec fermentum, ante vel scelerisque facilisis, ipsum diam lobortis felis, sit amet mollis est ligula at sapien. Pellentesque sit amet velit dui. Duis odio eros, tincidunt nec felis aliquet, maximus hendrerit risus. Nullam gravida consectetur metus, mollis pellentesque eros tempus id. Aliquam aliquet laoreet augue, egestas faucibus neque volutpat non. Aenean rutrum lorem at justo pulvinar, eu tincidunt libero eleifend. Donec tristique nisi leo, sit amet commodo metus feugiat sagittis. Duis iaculis rhoncus consectetur. Sed commodo leo vel nunc vestibulum, ut ullamcorper tortor mattis. Sed dignissim erat non suscipit congue. 
Sed dapibus egestas mauris in scelerisque. Nam consequat, mauris vel condimentum blandit, dui erat molestie risus, quis sodales leo est nec augue. Suspendisse potenti. Proin ut elit eget nibh dignissim interdum. Duis faucibus libero diam, eu condimentum nisi pulvinar aliquet. Maecenas sed hendrerit nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque orci quam, finibus vitae efficitur eu, interdum a lacus. Sed suscipit libero id enim tincidunt faucibus. Phasellus commodo venenatis aliquam. Suspendisse at nibh vel quam ultricies tempus ut eget nibh. Nunc pharetra mi eu lacus porta iaculis. In risus nisl, sollicitudin et ex vitae, pharetra tincidunt turpis. Fusce lacinia molestie feugiat. 
Quisque egestas diam non dolor pretium viverra. Integer suscipit nunc ut sollicitudin vulputate. Sed non dolor in dolor ultricies pharetra. Phasellus sed dui convallis lacus pharetra varius et ut lectus. Sed faucibus neque leo, vel porttitor lacus tristique hendrerit. Integer a interdum leo. Duis dignissim id metus quis euismod. Maecenas id nulla ut augue luctus scelerisque id at erat. Etiam rhoncus, risus rhoncus pellentesque finibus, tellus ipsum suscipit tellus, a accumsan ipsum ex sed tortor. In libero elit, consectetur in arcu sit amet, tempus molestie dui. Sed eleifend purus vitae lacus lobortis maximus. Sed in lectus id metus sagittis luctus eu non metus. Donec quam neque, fermentum sit amet tristique id, molestie in libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
In dictum sem quis porta laoreet. Sed laoreet lacus sit amet porta dictum. Nunc ac tempor diam. Quisque vel scelerisque lacus. Suspendisse vehicula lorem id ornare scelerisque. Vivamus ante enim, congue ac ante vel, varius tincidunt nunc. Phasellus maximus ut tellus eget lobortis. Ut at volutpat erat. Cras sem diam, interdum sit amet urna vel, luctus interdum eros. Duis at placerat turpis. Fusce aliquet tempor porttitor. Vivamus eu lacus orci. Aenean pulvinar sapien in arcu suscipit fermentum a at enim. Nulla facilisi. Aliquam sed orci in erat faucibus volutpat sit amet sed odio. Donec vel lectus a augue rutrum ornare. 
Ut suscipit ipsum metus, non efficitur lorem iaculis eu. Curabitur sed orci felis. Proin sed tellus nunc. Sed ac lorem dignissim, semper neque ac, feugiat dui. Nullam eu nunc sed neque dignissim tincidunt non at lacus. Maecenas viverra viverra enim in feugiat. Fusce eget porta nunc. Mauris eget nulla ipsum. Suspendisse ut fermentum lacus, id sodales odio. Morbi faucibus nunc eget nunc hendrerit placerat nec aliquam justo. Curabitur non ex iaculis, varius eros ut, gravida nunc. Etiam elementum faucibus lobortis. Nunc vulputate nibh in ullamcorper fermentum. Nulla tellus odio, commodo eu nunc eu, scelerisque semper nibh. 
Nulla sit amet enim nec metus mattis malesuada vitae eget neque. Vivamus ultrices, arcu ut lacinia aliquam, erat leo vehicula mauris, et vestibulum tortor tellus at erat. Quisque quis egestas augue, nec placerat velit. Vestibulum ultrices ex in dui facilisis, molestie auctor libero tristique. Integer at tellus egestas, condimentum eros vel, consequat orci. Aliquam quis consectetur leo, et convallis dolor. Praesent ut iaculis sapien. Ut odio nulla, vulputate eu lobortis in, feugiat eu est. In dictum finibus augue non imperdiet. 
Donec ac feugiat odio. Cras non sagittis purus, et viverra orci. Nullam sit amet massa sed enim faucibus finibus et ut eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In nec ipsum mattis, tincidunt nisi ut, cursus sapien. Sed egestas pharetra urna, sit amet blandit risus commodo nec. Vestibulum mollis fermentum velit. Ut nec fringilla dolor, lobortis congue ipsum. Nullam pretium mauris ut aliquam ullamcorper. Nullam felis orci, pharetra sed tellus nec, facilisis gravida nisi. 
Curabitur vel porttitor libero, quis pretium nisi. Phasellus feugiat metus quis commodo blandit. Curabitur est metus, egestas quis pharetra vel, ornare ac eros. Sed placerat quam et eros auctor vestibulum. Vestibulum porta maximus lacus, nec interdum nulla. Ut sit amet faucibus sapien, ut vulputate turpis. Pellentesque sollicitudin pharetra ipsum et consequat. Phasellus suscipit nisl ut justo tempus cursus. Ut porttitor orci vitae auctor pulvinar. Suspendisse consequat sagittis ipsum, at rutrum nunc condimentum vel. Phasellus mattis quam nec turpis laoreet, cursus porta nunc mattis. Vivamus risus diam, pretium id interdum id, ullamcorper sed tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc neque ex, pharetra eu mauris at, suscipit volutpat orci. Praesent semper diam eu tellus aliquet, a faucibus sem posuere. Vestibulum congue, nisi eu laoreet scelerisque, lectus velit molestie sem, ac vehicula massa orci ut tellus. Cras convallis et lacus id consequat. Nam odio erat, interdum vel facilisis id, cursus eget arcu. Nam commodo sit amet arcu in egestas. Nullam posuere ut leo id tincidunt. 
Donec odio felis, eleifend eu pretium at, ornare eu urna. Aliquam auctor efficitur sagittis. Maecenas eget mi nulla. Pellentesque id erat diam. Morbi sed nisi massa. Suspendisse quis dapibus est, et accumsan dui. In hac habitasse platea dictumst. Sed posuere pellentesque cursus. Vivamus ut lectus mi. Fusce luctus orci vel finibus iaculis. Phasellus tincidunt felis nisi, et rutrum quam vulputate a. Donec sed mi elit. Nulla a arcu urna. Maecenas lacus urna, lacinia id justo nec, aliquam ornare quam. Suspendisse eu sapien ut ante pretium lobortis id in leo. Morbi pretium elit augue, non vehicula erat finibus eget. 
Proin a dui quis mi viverra mollis at ut nisi. Donec fermentum, ante vel scelerisque facilisis, ipsum diam lobortis felis, sit amet mollis est ligula at sapien. Pellentesque sit amet velit dui. Duis odio eros, tincidunt nec felis aliquet, maximus hendrerit risus. Nullam gravida consectetur metus, mollis pellentesque eros tempus id. Aliquam aliquet laoreet augue, egestas faucibus neque volutpat non. Aenean rutrum lorem at justo pulvinar, eu tincidunt libero eleifend. Donec tristique nisi leo, sit amet commodo metus feugiat sagittis. Duis iaculis rhoncus consectetur. Sed commodo leo vel nunc vestibulum, ut ullamcorper tortor mattis. Sed dignissim erat non suscipit congue. 
Sed dapibus egestas mauris in scelerisque. Nam consequat, mauris vel condimentum blandit, dui erat molestie risus, quis sodales leo est nec augue. Suspendisse potenti. Proin ut elit eget nibh dignissim interdum. Duis faucibus libero diam, eu condimentum nisi pulvinar aliquet. Maecenas sed hendrerit nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque orci quam, finibus vitae efficitur eu, interdum a lacus. Sed suscipit libero id enim tincidunt faucibus. Phasellus commodo venenatis aliquam. Suspendisse at nibh vel quam ultricies tempus ut eget nibh. Nunc pharetra mi eu lacus porta iaculis. In risus nisl, sollicitudin et ex vitae, pharetra tincidunt turpis. Fusce lacinia molestie feugiat. 
Quisque egestas diam non dolor pretium viverra. Integer suscipit nunc ut sollicitudin vulputate. Sed non dolor in dolor ultricies pharetra. Phasellus sed dui convallis lacus pharetra varius et ut lectus. Sed faucibus neque leo, vel porttitor lacus tristique hendrerit. Integer a interdum leo. Duis dignissim id metus quis euismod. Maecenas id nulla ut augue luctus scelerisque id at erat. Etiam rhoncus, risus rhoncus pellentesque finibus, tellus ipsum suscipit tellus, a accumsan ipsum ex sed tortor. In libero elit, consectetur in arcu sit amet, tempus molestie dui. Sed eleifend purus vitae lacus lobortis maximus. Sed in lectus id metus sagittis luctus eu non metus. Donec quam neque, fermentum sit amet tristique id, molestie in libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
In dictum sem quis porta laoreet. Sed laoreet lacus sit amet porta dictum. Nunc ac tempor diam. Quisque vel scelerisque lacus. Suspendisse vehicula lorem id ornare scelerisque. Vivamus ante enim, congue ac ante vel, varius tincidunt nunc. Phasellus maximus ut tellus eget lobortis. Ut at volutpat erat. Cras sem diam, interdum sit amet urna vel, luctus interdum eros. Duis at placerat turpis. Fusce aliquet tempor porttitor. Vivamus eu lacus orci. Aenean pulvinar sapien in arcu suscipit fermentum a at enim. Nulla facilisi. Aliquam sed orci in erat faucibus volutpat sit amet sed odio. Donec vel lectus a augue rutrum ornare. 
Ut suscipit ipsum metus, non efficitur lorem iaculis eu. Curabitur sed orci felis. Proin sed tellus nunc. Sed ac lorem dignissim, semper neque ac, feugiat dui. Nullam eu nunc sed neque dignissim tincidunt non at lacus. Maecenas viverra viverra enim in feugiat. Fusce eget porta nunc. Mauris eget nulla ipsum. Suspendisse ut fermentum lacus, id sodales odio. Morbi faucibus nunc eget nunc hendrerit placerat nec aliquam justo. Curabitur non ex iaculis, varius eros ut, gravida nunc. Etiam elementum faucibus lobortis. Nunc vulputate nibh in ullamcorper fermentum. Nulla tellus odio, commodo eu nunc eu, scelerisque semper nibh. 
Nulla sit amet enim nec metus mattis malesuada vitae eget neque. Vivamus ultrices, arcu ut lacinia aliquam, erat leo vehicula mauris, et vestibulum tortor tellus at erat. Quisque quis egestas augue, nec placerat velit. Vestibulum ultrices ex in dui facilisis, molestie auctor libero tristique. Integer at tellus egestas, condimentum eros vel, consequat orci. Aliquam quis consectetur leo, et convallis dolor. Praesent ut iaculis sapien. Ut odio nulla, vulputate eu lobortis in, feugiat eu est. In dictum finibus augue non imperdiet. 
Donec ac feugiat odio. Cras non sagittis purus, et viverra orci. Nullam sit amet massa sed enim faucibus finibus et ut eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In nec ipsum mattis, tincidunt nisi ut, cursus sapien. Sed egestas pharetra urna, sit amet blandit risus commodo nec. Vestibulum mollis fermentum velit. Ut nec fringilla dolor, lobortis congue ipsum. Nullam pretium mauris ut aliquam ullamcorper. Nullam felis orci, pharetra sed tellus nec, facilisis gravida nisi. 
Curabitur vel porttitor libero, quis pretium nisi. Phasellus feugiat metus quis commodo blandit. Curabitur est metus, egestas quis pharetra vel, ornare ac eros. Sed placerat quam et eros auctor vestibulum. Vestibulum porta maximus lacus, nec interdum nulla. Ut sit amet faucibus sapien, ut vulputate turpis. Pellentesque sollicitudin pharetra ipsum et consequat. Phasellus suscipit nisl ut justo tempus cursus. Ut porttitor orci vitae auctor pulvinar. Suspendisse consequat sagittis ipsum, at rutrum nunc condimentum vel. Phasellus mattis quam nec turpis laoreet, cursus porta nunc mattis. Vivamus risus diam, pretium id interdum id, ullamcorper sed tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc neque ex, pharetra eu mauris at, suscipit volutpat orci. Praesent semper diam eu tellus aliquet, a faucibus sem posuere. Vestibulum congue, nisi eu laoreet scelerisque, lectus velit molestie sem, ac vehicula massa orci ut tellus. Cras convallis et lacus id consequat. Nam odio erat, interdum vel facilisis id, cursus eget arcu. Nam commodo sit amet arcu in egestas. Nullam posuere ut leo id tincidunt. 
Donec odio felis, eleifend eu pretium at, ornare eu urna. Aliquam auctor efficitur sagittis. Maecenas eget mi nulla. Pellentesque id erat diam. Morbi sed nisi massa. Suspendisse quis dapibus est, et accumsan dui. In hac habitasse platea dictumst. Sed posuere pellentesque cursus. Vivamus ut lectus mi. Fusce luctus orci vel finibus iaculis. Phasellus tincidunt felis nisi, et rutrum quam vulputate a. Donec sed mi elit. Nulla a arcu urna. Maecenas lacus urna, lacinia id justo nec, aliquam ornare quam. Suspendisse eu sapien ut ante pretium lobortis id in leo. Morbi pretium elit augue, non vehicula erat finibus eget. 
Proin a dui quis mi viverra mollis at ut nisi. Donec fermentum, ante vel scelerisque facilisis, ipsum diam lobortis felis, sit amet mollis est ligula at sapien. Pellentesque sit amet velit dui. Duis odio eros, tincidunt nec felis aliquet, maximus hendrerit risus. Nullam gravida consectetur metus, mollis pellentesque eros tempus id. Aliquam aliquet laoreet augue, egestas faucibus neque volutpat non. Aenean rutrum lorem at justo pulvinar, eu tincidunt libero eleifend. Donec tristique nisi leo, sit amet commodo metus feugiat sagittis. Duis iaculis rhoncus consectetur. Sed commodo leo vel nunc vestibulum, ut ullamcorper tortor mattis. Sed dignissim erat non suscipit congue. 
Sed dapibus egestas mauris in scelerisque. Nam consequat, mauris vel condimentum blandit, dui erat molestie risus, quis sodales leo est nec augue. Suspendisse potenti. Proin ut elit eget nibh dignissim interdum. Duis faucibus libero diam, eu condimentum nisi pulvinar aliquet. Maecenas sed hendrerit nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque orci quam, finibus vitae efficitur eu, interdum a lacus. Sed suscipit libero id enim tincidunt faucibus. Phasellus commodo venenatis aliquam. Suspendisse at nibh vel quam ultricies tempus ut eget nibh. Nunc pharetra mi eu lacus porta iaculis. In risus nisl, sollicitudin et ex vitae, pharetra tincidunt turpis. Fusce lacinia molestie feugiat. 
Quisque egestas diam non dolor pretium viverra. Integer suscipit nunc ut sollicitudin vulputate. Sed non dolor in dolor ultricies pharetra. Phasellus sed dui convallis lacus pharetra varius et ut lectus. Sed faucibus neque leo, vel porttitor lacus tristique hendrerit. Integer a interdum leo. Duis dignissim id metus quis euismod. Maecenas id nulla ut augue luctus scelerisque id at erat. Etiam rhoncus, risus rhoncus pellentesque finibus, tellus ipsum suscipit tellus, a accumsan ipsum ex sed tortor. In libero elit, consectetur in arcu sit amet, tempus molestie dui. Sed eleifend purus vitae lacus lobortis maximus. Sed in lectus id metus sagittis luctus eu non metus. Donec quam neque, fermentum sit amet tristique id, molestie in libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
In dictum sem quis porta laoreet. Sed laoreet lacus sit amet porta dictum. Nunc ac tempor diam. Quisque vel scelerisque lacus. Suspendisse vehicula lorem id ornare scelerisque. Vivamus ante enim, congue ac ante vel, varius tincidunt nunc. Phasellus maximus ut tellus eget lobortis. Ut at volutpat erat. Cras sem diam, interdum sit amet urna vel, luctus interdum eros. Duis at placerat turpis. Fusce aliquet tempor porttitor. Vivamus eu lacus orci. Aenean pulvinar sapien in arcu suscipit fermentum a at enim. Nulla facilisi. Aliquam sed orci in erat faucibus volutpat sit amet sed odio. Donec vel lectus a augue rutrum ornare. 
Ut suscipit ipsum metus, non efficitur lorem iaculis eu. Curabitur sed orci felis. Proin sed tellus nunc. Sed ac lorem dignissim, semper neque ac, feugiat dui. Nullam eu nunc sed neque dignissim tincidunt non at lacus. Maecenas viverra viverra enim in feugiat. Fusce eget porta nunc. Mauris eget nulla ipsum. Suspendisse ut fermentum lacus, id sodales odio. Morbi faucibus nunc eget nunc hendrerit placerat nec aliquam justo. Curabitur non ex iaculis, varius eros ut, gravida nunc. Etiam elementum faucibus lobortis. Nunc vulputate nibh in ullamcorper fermentum. Nulla tellus odio, commodo eu nunc eu, scelerisque semper nibh. 
Nulla sit amet enim nec metus mattis malesuada vitae eget neque. Vivamus ultrices, arcu ut lacinia aliquam, erat leo vehicula mauris, et vestibulum tortor tellus at erat. Quisque quis egestas augue, nec placerat velit. Vestibulum ultrices ex in dui facilisis, molestie auctor libero tristique. Integer at tellus egestas, condimentum eros vel, consequat orci. Aliquam quis consectetur leo, et convallis dolor. Praesent ut iaculis sapien. Ut odio nulla, vulputate eu lobortis in, feugiat eu est. In dictum finibus augue non imperdiet. 
Donec ac feugiat odio. Cras non sagittis purus, et viverra orci. Nullam sit amet massa sed enim faucibus finibus et ut eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In nec ipsum mattis, tincidunt nisi ut, cursus sapien. Sed egestas pharetra urna, sit amet blandit risus commodo nec. Vestibulum mollis fermentum velit. Ut nec fringilla dolor, lobortis congue ipsum. Nullam pretium mauris ut aliquam ullamcorper. Nullam felis orci, pharetra sed tellus nec, facilisis gravida nisi. 
Curabitur vel porttitor libero, quis pretium nisi. Phasellus feugiat metus quis commodo blandit. Curabitur est metus, egestas quis pharetra vel, ornare ac eros. Sed placerat quam et eros auctor vestibulum. Vestibulum porta maximus lacus, nec interdum nulla. Ut sit amet faucibus sapien, ut vulputate turpis. Pellentesque sollicitudin pharetra ipsum et consequat. Phasellus suscipit nisl ut justo tempus cursus. Ut porttitor orci vitae auctor pulvinar. Suspendisse consequat sagittis ipsum, at rutrum nunc condimentum vel. Phasellus mattis quam nec turpis laoreet, cursus porta nunc mattis. Vivamus risus diam, pretium id interdum id, ullamcorper sed tellus. </p>
      </div>
  </div>